---
- name: Deploy Azure Lab Resources
  hosts: localhost
  vars:
    AZURE_REGION: eastus2
    AZURE_TENANT: "{{ lookup('env', 'AZURE_TENANT') }}"
    RESGROUP_NAME: ansible-lab01
    SPN_OBJECT_ID: "4b3736d4-64a9-4fc0-963c-31b19487a037"
    SPN_APP_ID: "{{ lookup('env', 'AZURE_CLIENT_ID') }}"
    VMTags: 
      environment: lab
      owner: ansible
  tasks:
    
    - name: Execute bash script to set environment variables
      script: ./set_envvars.sh

    - name: Collect Data
      debug:
        msg: "Subscription ID: {{ lookup('env', 'AZURE_SUBSCRIPTION_ID') }}, Client ID: {{ lookup('env', 'AZURE_CLIENT_ID') }}, Tenant: {{ lookup('env', 'AZURE_TENANT') }}, Secret: {{ lookup('env', 'AZURE_SECRET') }}"
      when: lookup('env', 'AZURE_SUBSCRIPTION_ID') | length > 0    

    - name: Create a resource group
      azure.azcollection.azure_rm_resourcegroup:
        name: "{{ RESGROUP_NAME }}"
        location: "{{ AZURE_REGION }}"
        tags: "{{ VMTags }}"
      register: azRG

    - name: Deploy Azure KeyVault 
      azure.azcollection.azure_rm_keyvault:
        vault_name: "ansiblelabs101kv"
        resource_group: "{{ RESGROUP_NAME }}"
        location: "{{ AZURE_REGION }}"
        enabled_for_deployment: true
        enable_rbac_authorization: true
        vault_tenant: "{{ lookup ('env', 'AZURE_TENANT') }}"
        sku:
          name: standard
          family: A
        tags: "{{ VMTags }}"
      register: azKV

    - name: Configure SPN as Keyvault Contributor
      azure.azcollection.azure_rm_roleassignment:
        role_definition_id: "/subscriptions/{{ lookup('env', 'AZURE_SUBSCRIPTION_ID') }}/providers/Microsoft.Authorization/roleDefinitions/00482a5a-887f-4fb3-b363-3b7fe8e74483"
        assignee_object_id: "{{ SPN_OBJECT_ID }}"
        scope: "/subscriptions/{{ lookup('env', 'AZURE_SUBSCRIPTION_ID') }}/"
        state: present
      register: azRole