---
- name: Deploy Azure Lab Resources
  hosts: localhost
  vars:
    AZURE_REGION: eastus2
    AZURE_TENANT: "{{ lookup ('env', 'AZURE_TENANT') }}"
    RESGROUP_NAME: ansible-lab01
    SPN_APP_ID: "{{ lookup ('env', 'AZURE_CLIENT_ID') }}"
  tasks:
    - name: Create a resource group
      azure.azcollection.azure_rm_resourcegroup:
        name: "{{ RESGROUP_NAME }}"
        location: "{{ AZURE_REGION }}"
        tags:
          environment: lab
          owner: ansible
      register: azRG

    - name: Deploy Azure KeyVault 
      azure.azcollection.azure_rm_keyvault:
        vault_name: ansiblelab01kv
        resource_group: "{{ RESGROUP_NAME }}"
        location: "{{ AZURE_REGION }}"
        enabled_for_deployment: true
        enable_rbac_authorization: true
        vault_tenant: "{{ lookup ('env', 'AZURE_TENANT') }}"
        sku:
          name: standard
          family: A
        tags:
          environment: lab
          owner: ansible
      register: azKV

    - name: Configure SPN as Keyvault Contributor
      azure.azcollection.azure_rm_roleassignment:
        role_definition_id:
          "/subscriptions/{{ lookup ('env', 'AZURE_SUBSCRIPTION_ID') }}/providers/Microsoft.Authorization/roleDefinitions/f25e0fa2-a7c8-4377-a976-54943a77a395"
        assignee_object_id: "{{ SPN_APP_ID }}"
        scope: "/subscriptions/{{ lookup ('env', 'AZURE_SUBSCRIPTION_ID') }}/resourceGroups/{{ RESGROUP_NAME }}/providers/Microsoft.KeyVault/vaults/ansiblelab01kv"