---
- name: Ansible Demo Windows
  hosts: webservers
  connection: winrm
  gather_facts: yes
  vars:
    URL: "ansibledemo.msftlabs.work"
    PATH: 'c:\inetpub\wwwroot\v1'
  collections:
    - community.windows
    - ansible.windows
  
  tasks:
    - name: Install IIS (Web-Server and Web-Common-Http)
      ansible.windows.win_feature:
        name:
          - Web-Server
          - Web-Common-Http
        state: present
        include_management_tools: true
      register: iis

    - name: Remove Default WebSite
      community.windows.win_iis_website:
        name: Default Web Site
        state: absent
      
    - name: Create App Directory
      ansible.windows.win_file:
        path: "{{ PATH }}"
        state: directory
      register: appDirCreate

    - name: Copy App Files
      ansible.windows.win_copy:
        src: app_code/index.html
        dest: c:\inetpub\wwwroot\v1\index.html
      register: appFileCopy
    
    - name: Create a new application pool in 'Started' state
      community.windows.win_iis_webapppool:
        name: AnsibleAppPool
        state: started
      register: appPoolCreate

    - name: validate the app pool creation
      debug:
        msg: "{{ appPoolCreate }}"

    - name: Configure WebSite
      community.windows.win_iis_website:
        name: "Ansible 101 Demo"
        state: started
        physical_path: "{{ PATH }}"
        port: 80
        hostname: "{{ URL }}"
        application_pool: "{{ appPoolCreate.info.name }}"
      register: webSiteConfig 
      