---
- name: test ansible installation
  hosts: webservers
  connection: winrm
  gather_facts: yes
  vars:
    TEST: "World"

  tasks:
    - name: Print Hello MSG
      debug:
        msg: "Hello from {{ ansible_facts['nodename'] }} running on {{ ansible_facts['os_family'] }}"
        

    - name: Print Hello MSG
      debug:
        msg: 'Hello {{ TEST }}'