---
- name: Install Ansible on Ubuntu 18.04
  hosts: all
  become: yes
  gather_facts: yes
  vars:
    github_repo: "BenTheCloudGuy/lab-ansible-101"
    keyvault_name: "ansibleDemoKV"
    GITHUB_TOKEN: ""
    runner_name: "ansible-self-hosted-runner"
    runner_labels: "ubuntu, self-hosted"
    runner_version: "2.321.0"  

  tasks:

    # Install Required Packages
    - name: Update apt package list
      apt:
        update_cache: yes

    - name: Install software-properties-common
      apt:
        name: 
          - software-properties-common
          - curl
          - tar
          - jq
        state: present

  
    # Install Ansible
    - name: Add Ansible PPA
      apt_repository:
        repo: ppa:ansible/ansible
        state: present

    - name: Install Ansible
      apt:
        name: ansible
        state: present

    - name: Verify Ansible installation
      command: ansible --version
      register: ansible_version

    - name: Display Ansible version
      debug:
        msg: "Ansible version: {{ ansible_version }}"

