---
- name: test ansible installation
  hosts: localhost
  gather_facts: yes
  vars:
    TEST: "World"
    
  tasks:
    - name: Print Hello MSG
      ansible.builtin.command:
        cmd: ls
      register: testing

    - name: Print Hello MSG
      debug: 
        msg: "{{ testing.stdout_lines }}"