name: Test WinRM
on:
    push:
        branches: [main]
        paths:
            - 'ansible/**'
            - 'demo/**'
            - '.github/workflows/ansible-demo.yml'

jobs:
    ansible-demo:
        runs-on: [self-hosted, ansible]
        steps:
            - name: Checkout Repository
              uses: actions/checkout@v1

            - name: Current User
              run: whoami

            - name: Get PATH
              run: echo $PATH
            
            - name: Test Ansible
              run: ansible --version
            


