name: Ansible 101 Demo
on:
    push:
        branches: [main]
        paths:
            - 'ansible/**'
            - 'demo/**'
            - '.github/workflows/ansible-demo.yml'

jobs:
    ansible-demo:
        runs-on: [self-hosted, ansible]
        steps:
            - name: Checkout Repository
              uses: actions/checkout@v1

            - name: Test Ansible
              run: ansible --version
            
            - name: Run Test Windows Playbook
              run: ansible-playbook ansible/ansible-demo.yml
